### ISSUE TITLE
ZOFE Compatability (Native?)

### ISSUE THREAD

**Issue by TehFishey** [TehFishey/stellaris-crisis-managers#5]
With ZOFE updated, the old compat mod should be updated as well. This is mostly for posterity/cleanliness (the old compat mod actually works fine as-is). 

If possible, it would be nice to include the compat feature natively in the sleeper edition/other mods. Does ZOFE flip any global flags that can be used to check if it's active?

**Comment by F1r3Pr1nc3** [comment]
End- and Mid-Game have now included the native scripted triggers.

**Comment by F1r3Pr1nc3** [comment]
Finished with Sleeper 3.0 https://steamcommunity.com/sharedfiles/filedetails/?id=2577705378
