### ISSUE TITLE
Multiple FE Sleeper awakening issues?

### ISSUE THREAD

**Issue by TehFishey** [TehFishey/stellaris-crisis-managers#7]
A bug was reported in the sleeper edition (https://steamcommunity.com/workshop/filedetails/discussion/2036461392/2146469724197004978/) where subsequent Fallen Empires could not be awakened after the first one was triggered. This is apparently an ongoing/inherited issue from the previous version of Crisis Manager?

Confirm/reproduce this bug, and fix it if possible.

**Comment by F1r3Pr1nc3** [comment]
I've looked in to his save. The only bug there is, you can choose the option for WiH when no requirements are valid. In fact there was only 1 valid FE.  And there was also no valid AE, as the 3 other FE were as follows: 1 Machine, 2 already dead without navy (there is in fact a trigger for this) and 3rd AE **in war**. So I'll simply extend the validity trigger for this option.

**Comment by F1r3Pr1nc3** [comment]
Should be fixed with the new version (even it was a 50:50 chance, as the first FE (SleeperA)  had no navy but gets some on awaken): https://steamcommunity.com/sharedfiles/filedetails/?id=2577705378
